### ISSUE TITLE
Is version 2.0.0 released?

### ISSUE THREAD

**Issue by gspr** [anigmetov/hera#10]
Is the changelog entry from commit 5d36812d275584a5e973459dd9bfe54af0bd1ca4 meant to signify Hera 2.0.0? If so, could you please tag the release if so?

**Comment by gspr** [comment]
Ping. With GUDHI 3.7 released, it's becoming quite crucial to have this issue answered for the sake of having an updated Debian package for GUDHI.

**Comment by anigmetov** [comment]
Oh, I am very sorry --- I completely forgot about this issue. Yes, it should be version 2, I pushed the tag.
