### ISSUE TITLE
diagram_reader.h differs between wasserstein and bottleneck

### ISSUE THREAD

**Issue by mglisse** [anigmetov/hera#2]
Hello,
I notice that wasserstein and bottleneck both have include/diagram_reader.h, but with different contents. For a C++ code that wants to use both wasserstein and bottleneck, what is the recommended approach? I am going to use them in separate translation units for now to work around the issue, but I believe @gspr is likely to hit the same issue for his Debian Hera package.

**Comment by gspr** [comment]
Marc Glisse <notifications@github.com> writes:

> I notice that wasserstein and bottleneck both have include/diagram_reader.h, but with different contents. For a C++ code that wants to use both wasserstein and bottleneck, what is the recommended approach? I am going to use them in separate translation units for now to work around the issue, but I believe @gspr is likely to hit the same issue for his Debian Hera package.

It would perhaps also be nice if code that is intended to be the same
between bottleneck and Wasserstein were only shipped in one
copy. Perhaps the source tree could be restructured as something like

 include/
 include/bottleneck/
 include/wasserstein/

were common files go in the first?

**Comment by mglisse** [comment]
I think this is fixed now.
