### ISSUE TITLE
Versioned releases?

### ISSUE THREAD

**Issue by gspr** [anigmetov/hera#6]
Would you consider making versioned releases of Hera? This would greatly help with e.g. Debian's Hera packages (present in Debian as a dependency of GUDHI).

For example, it's hard to tell whether the latest "cleanup commit" warrants a new version of the package in Debian or not. Versioned releases would clarify this.

**Comment by anigmetov** [comment]
Yes, it is a good idea, I'll do it. Sorry for the confusion. Last commit is not a new version at all. I am going to add some more functionality soon, and I'll add version info then.

**Comment by anigmetov** [comment]
Yes, it is a good idea, I'll do it. Sorry for the confusion. Last commit is not a new version at all. I am going to add some more functionality soon, and I'll add version info then.

**Comment by gspr** [comment]
Arnur Nigmetov ***@***.***> writes:

> Yes, it is a good idea, I'll do it. Sorry for the confusion. Last commit is not a new version at all. I am going to
> add some more functionality soon, and I'll add version info then.

Am I correct in thinking that the v1.0.0 tag constituted a versioned
release? If so, this is very helpful – I just want to confirm that it
was the intention.
