### ISSUE TITLE
Spelling corrections for "extern" directories

### ISSUE THREAD

**Issue by albert-github** [anigmetov/hera#9]
In the code there are some sub-directories  in the `extern` part  (i.e. Catch2 and phat) that have some obvious spelling errors.

Question is should they be corrected here or upstream and in case of upstream where to find the repositories

**Comment by anigmetov** [comment]
I don't think it's a good idea to correct them here. You can try git@github.com:catchorg/Catch2.git and git@github.com:blazs/phat.git .

Thanks

**Comment by albert-github** [comment]
Thanks for the answer.
- When I would create PRs in those repositories, would you pull the changes in later on as well (i.e. update the used version in hera)?
   -  especially as the `phat` project looks like to be a bit dead
- Can you change your comment and point to:
   - https://github.com/catchorg/Catch2
   - https://github.com/blazs/phat
